# CMake generated Testfile for 
# Source directory: /Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples
# Build directory: /Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/cmake_cache/src/lr-wpan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-lr-wpan-data "ns3.38-lr-wpan-data-debug")
set_tests_properties(ctest-lr-wpan-data PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;14;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-mlme "ns3.38-lr-wpan-mlme-debug")
set_tests_properties(ctest-lr-wpan-mlme PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;14;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-packet-print "ns3.38-lr-wpan-packet-print-debug")
set_tests_properties(ctest-lr-wpan-packet-print PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;14;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-phy-test "ns3.38-lr-wpan-phy-test-debug")
set_tests_properties(ctest-lr-wpan-phy-test PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;14;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-ed-scan "ns3.38-lr-wpan-ed-scan-debug")
set_tests_properties(ctest-lr-wpan-ed-scan PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;14;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-active-scan "ns3.38-lr-wpan-active-scan-debug")
set_tests_properties(ctest-lr-wpan-active-scan PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;14;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-error-distance-plot "ns3.38-lr-wpan-error-distance-plot-debug")
set_tests_properties(ctest-lr-wpan-error-distance-plot PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;21;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-error-model-plot "ns3.38-lr-wpan-error-model-plot-debug")
set_tests_properties(ctest-lr-wpan-error-model-plot PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;28;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-bootstrap "ns3.38-lr-wpan-bootstrap-debug")
set_tests_properties(ctest-lr-wpan-bootstrap PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;35;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-per-plot "ns3.38-lr-wpan-per-plot-debug")
set_tests_properties(ctest-lr-wpan-per-plot PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;42;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lr-wpan/examples/CMakeLists.txt;0;")
