# CMake generated Testfile for 
# Source directory: /Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/sixlowpan/examples
# Build directory: /Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/cmake_cache/src/sixlowpan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-example-sixlowpan "ns3.38-example-sixlowpan-debug")
set_tests_properties(ctest-example-sixlowpan PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/sixlowpan/examples/CMakeLists.txt;1;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan "ns3.38-example-ping-lr-wpan-debug")
set_tests_properties(ctest-example-ping-lr-wpan PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/sixlowpan/examples/CMakeLists.txt;12;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan-beacon "ns3.38-example-ping-lr-wpan-beacon-debug")
set_tests_properties(ctest-example-ping-lr-wpan-beacon PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/sixlowpan/examples/CMakeLists.txt;23;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan-mesh-under "ns3.38-example-ping-lr-wpan-mesh-under-debug")
set_tests_properties(ctest-example-ping-lr-wpan-mesh-under PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/sixlowpan/examples/CMakeLists.txt;34;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/sixlowpan/examples/CMakeLists.txt;0;")
