# CMake generated Testfile for 
# Source directory: /Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples
# Build directory: /Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/cmake_cache/src/lorawan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-simple-network-example "ns3.38-simple-network-example-debug")
set_tests_properties(ctest-simple-network-example PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples/CMakeLists.txt;1;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-network-server-example "ns3.38-network-server-example-debug")
set_tests_properties(ctest-network-server-example PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples/CMakeLists.txt;8;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-complete-network-example "ns3.38-complete-network-example-debug")
set_tests_properties(ctest-complete-network-example PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples/CMakeLists.txt;16;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-adr-example "ns3.38-adr-example-debug")
set_tests_properties(ctest-adr-example PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples/CMakeLists.txt;24;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-lorawan-energy-model-example "ns3.38-lorawan-energy-model-example-debug")
set_tests_properties(ctest-lorawan-energy-model-example PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples/CMakeLists.txt;32;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-aloha-throughput "ns3.38-aloha-throughput-debug")
set_tests_properties(ctest-aloha-throughput PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples/CMakeLists.txt;40;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-parallel-reception-example "ns3.38-parallel-reception-example-debug")
set_tests_properties(ctest-parallel-reception-example PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples/CMakeLists.txt;48;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-frame-counter-update "ns3.38-frame-counter-update-debug")
set_tests_properties(ctest-frame-counter-update PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples/CMakeLists.txt;56;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/lorawan/examples/CMakeLists.txt;0;")
