# CMake generated Testfile for 
# Source directory: /Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/click/examples
# Build directory: /Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/cmake_cache/src/click/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-nsclick-simple-lan "ns3.38-nsclick-simple-lan-debug")
set_tests_properties(ctest-nsclick-simple-lan PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/click/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/click/examples/CMakeLists.txt;1;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/click/examples/CMakeLists.txt;0;")
add_test(ctest-nsclick-raw-wlan "ns3.38-nsclick-raw-wlan-debug")
set_tests_properties(ctest-nsclick-raw-wlan PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/click/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/click/examples/CMakeLists.txt;11;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/click/examples/CMakeLists.txt;0;")
add_test(ctest-nsclick-udp-client-server-csma "ns3.38-nsclick-udp-client-server-csma-debug")
set_tests_properties(ctest-nsclick-udp-client-server-csma PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/click/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/click/examples/CMakeLists.txt;21;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/click/examples/CMakeLists.txt;0;")
add_test(ctest-nsclick-udp-client-server-wifi "ns3.38-nsclick-udp-client-server-wifi-debug")
set_tests_properties(ctest-nsclick-udp-client-server-wifi PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/click/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/click/examples/CMakeLists.txt;31;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/click/examples/CMakeLists.txt;0;")
add_test(ctest-nsclick-routing "ns3.38-nsclick-routing-debug")
set_tests_properties(ctest-nsclick-routing PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/click/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/click/examples/CMakeLists.txt;41;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/click/examples/CMakeLists.txt;0;")
add_test(ctest-nsclick-defines "ns3.38-nsclick-defines-debug")
set_tests_properties(ctest-nsclick-defines PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/click/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/click/examples/CMakeLists.txt;51;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/click/examples/CMakeLists.txt;0;")
