# CMake generated Testfile for 
# Source directory: /Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/mobility/examples
# Build directory: /Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/cmake_cache/src/mobility/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-bonnmotion-ns2-example "ns3.38-bonnmotion-ns2-example-debug")
set_tests_properties(ctest-bonnmotion-ns2-example PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-main-random-topology "ns3.38-main-random-topology-debug")
set_tests_properties(ctest-main-random-topology PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-main-random-walk "ns3.38-main-random-walk-debug")
set_tests_properties(ctest-main-random-walk PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-ns2-mobility-trace "ns3.38-ns2-mobility-trace-debug")
set_tests_properties(ctest-ns2-mobility-trace PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-main-grid-topology "ns3.38-main-grid-topology-debug")
set_tests_properties(ctest-main-grid-topology PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/mobility/examples/CMakeLists.txt;19;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-mobility-trace-example "ns3.38-mobility-trace-example-debug")
set_tests_properties(ctest-mobility-trace-example PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/mobility/examples/CMakeLists.txt;28;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-reference-point-group-mobility-example "ns3.38-reference-point-group-mobility-example-debug")
set_tests_properties(ctest-reference-point-group-mobility-example PROPERTIES  WORKING_DIRECTORY "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/mobility/examples/CMakeLists.txt;37;build_lib_example;/Users/aimanmeenai/Desktop/CN_project/project/trial3/bake/source/ns-3.38/src/mobility/examples/CMakeLists.txt;0;")
